
document.write('<p>');
document.write('<a href="/OpenSource-GameList">home</a>');
document.write(' - ');
document.write('<a href="/OpenSource-GameList/tag/casual">casual</a>');
document.write(' - ');
document.write('<a href="/OpenSource-GameList/tag/android">android</a>');
document.write(' - ');
document.write('<a href="/OpenSource-GameList/tag/online_multiplayer">online multiplayer</a>');
document.write(' - ');
document.write('<a href="/OpenSource-GameList/tag/local_multiplayer">local multiplayer</a>');
document.write(' - ');
document.write('<a href="/OpenSource-GameList/tag/on_device_multiplayer">multiplayer on a device</a>');
document.write(' - ');
document.write('<a href="/OpenSource-GameList/tag/rpg">rpg</a>');
document.write(' - ');
document.write('<a href="/OpenSource-GameList/tag/card">card</a>');
document.write(' - ');
document.write('<a href="/OpenSource-GameList/tag/shooter">shooter</a>');
document.write(' - ');
document.write('<a href="/OpenSource-GameList/tag/sandbox/">sandbox</a>');
document.write(' - ');
document.write('<a href="/OpenSource-GameList/tag/rhythm">rhythm</a>');
document.write(' - ');
document.write('<a href="/OpenSource-GameList/tag/strategy">strategy</a>');
document.write(' - ');
document.write('<a href="/OpenSource-GameList/tag/simulation">simulation</a>');
document.write(' - ');
document.write('<a href="/OpenSource-GameList/tag/plataformer">plataformer</a>');
document.write(' - ');
document.write('<a href="/OpenSource-GameList/tag/racing">racing</a>');
document.write(' - ');
document.write('<a href="/OpenSource-GameList/tag/minigames">minigames</a>');
document.write(' - ');
document.write('<a href="/OpenSource-GameList/tag/education">education</a>');
document.write('</p>');
