
document.write('<p>');
document.write('<a href="/OpenSource-GameList">home</a>');
document.write(' - ');
document.write('<a href="/OpenSource-GameList/tag/sandbox/">sandbox</a>');
document.write(' - ');
document.write('<a href="/OpenSource-GameList/tag/rhythm">rhythm</a>');
document.write(' - ');
document.write('<a href="/OpenSource-GameList/tag/strategy">strategy</a>');
document.write(' - ');
document.write('<a href="/OpenSource-GameList/tag/shooter">shooter</a>');
document.write(' - ');
document.write('<a href="/OpenSource-GameList/tag/simulation">simulation</a>');
document.write(' - ');
document.write('<a href="/OpenSource-GameList/tag/plataformer">plataformer</a>');
document.write(' - ');
document.write('<a href="/OpenSource-GameList/tag/racing">racing</a>');
document.write(' - ');
document.write('<a href="/OpenSource-GameList/tag/minigames">minigames</a>');
document.write('</p>');
